# Используем официальный образ Airflow
FROM apache/airflow:2.10.5-python3.11

# Переключаемся на root для установки системных пакетов
USER root

# Установка curl для healthcheck и других полезных утилит
RUN apt-get update && apt-get install -y \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Возвращаемся к пользователю airflow
USER airflow

# Копируем файл с зависимостями
COPY requirements.txt /requirements.txt

# Устанавливаем Python зависимости
RUN pip install --no-cache-dir -r /requirements.txt

# Копируем DAG'и
COPY ./dags /opt/airflow/dags

# Копируем .env файл (опционально)
COPY .env /opt/airflow/.env

# Отключаем примеры DAG'ов (для чистоты)
ENV AIRFLOW__CORE__LOAD_EXAMPLES=False

# Эту команду можно переопределить при запуске контейнера
CMD ["airflow", "webserver"]